module.exports = {
	INVALID_PARAMETERS : "INVALID_PARAMETERS",
	NOT_AUTHORIZED : "NOT_AUTHORIZED",
	TOKEN_REQUIRED : "TOKEN_REQUIRED",
	TOKEN_EXPIRED : "TOKEN_EXPIRED",
	INVALID_TOKEN : "INVALID_TOKEN",
	USER_NOT_FIND : "USER_NOT_FIND",
	USER_EXIST : "USER_EXIST",
	AUTHORIZED : "AUTHORIZED",
	SUCCESS : "SUCCESS"
};